-- begin COURSES_QUESTION
alter table COURSES_QUESTION add constraint FK_COURSES_QUESTION_ON_TEST foreign key (TEST_ID) references COURSES_TEST(ID)^
create index IDX_COURSES_QUESTION_ON_TEST on COURSES_QUESTION (TEST_ID)^
-- end COURSES_QUESTION
-- begin COURSES_COURSE
alter table COURSES_COURSE add constraint FK_COURSES_COURSE_ON_SPECIALIZATION foreign key (SPECIALIZATION_ID) references COURSES_SPECIALIZATION(ID)^
create index IDX_COURSES_COURSE_ON_SPECIALIZATION on COURSES_COURSE (SPECIALIZATION_ID)^
-- end COURSES_COURSE
-- begin COURSES_TEST
alter table COURSES_TEST add constraint FK_COURSES_TEST_ON_COURSE foreign key (COURSE_ID) references COURSES_COURSE(ID)^
create index IDX_COURSES_TEST_ON_COURSE on COURSES_TEST (COURSE_ID)^
-- end COURSES_TEST
